### ISSUE TITLE
Not working in Scala

### ISSUE THREAD

**Issue by nexnex300** [McFoggy/cssfx#37]
I've tried running CSSFX in conjunction with Scala but I haven't had any luck so far. I thought sbt might be the issue but it doesn't work with Gradle either. 
I don't know if you're interested in Scala but do you have any idea what the issue might be?

**Comment by McFoggy** [comment]
CSSFX defines a mapping between resources & source files.
By default CSSFX tries its best to find a mapping that matches the end user setup. This is done via a list of [URIToPathConverter](https://github.com/McFoggy/cssfx/blob/master/src/main/java/fr/brouillard/oss/cssfx/api/URIToPathConverter.java#L32) defined in [CSSFX](https://github.com/McFoggy/cssfx/blob/master/src/main/java/fr/brouillard/oss/cssfx/CSSFX.java#L150) to match by default usages from [Maven, Gradle, Jar, Intellij](https://github.com/McFoggy/cssfx/blob/master/src/main/java/fr/brouillard/oss/cssfx/impl/URIToPathConverters.java#L192)

If it does not work in SBT, it is probably because the matching between classes/sources is not resolved by the default converters.
You can add your own converter via:
- [`CSSFX.addConverter()`](https://github.com/McFoggy/cssfx/blob/master/src/main/java/fr/brouillard/oss/cssfx/CSSFX.java#L139)
- [`CSSFXConfig.addConverter()`](https://github.com/McFoggy/cssfx/blob/master/src/main/java/fr/brouillard/oss/cssfx/CSSFX.java#L185)

> but it doesn't work with Gradle either

As I don't use it, I did not check if gradle layout has changed since it was first introduced.
